name: foodlink
description: "Food Waste Donation Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1 
  page_transition: ^2.1.0
  lottie: ^3.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
