name: food_link_app
description: "FoodLink - Premium Food Donation & Management Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # UI and fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Networking
  http: ^1.2.2

  # Local storage and preferences
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.0.2

  # Utilities
  intl: ^0.20.2
  connectivity_plus: ^7.0.0

  # UI enhancements
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Device features
  image_picker: ^1.0.4
  google_maps_flutter: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/